### ISSUE TITLE
🐛

### ISSUE THREAD

**Issue by ZKBL** [cloudflare/cloudflared#1018]
**Describe the bug**
---
My response to an http request is an application/octet-stream, using the cloudflare tunnel always receives the full packet before transmission, does anyone know what the situation is?

**To Reproduce**
---
only created the tunnel, configured the public host, not enabled the private network,

forwarded my http requests to my server tha build with  this **https://github.com/Chanzhaoyu/chatgpt-web**

Express an vue3 

If it's an issue with Cloudflare Tunnel:
---
4. Tunnel ID :  
```a84fe929-20ee-426c-8690-a6389ec60268```
6. cloudflared config: 

```yaml
url: http://127.0.0.1:3002
tunnel: a84fe929-20ee-426c-8690-a6389ec60268
credentials-file: /path to my cert-file/cert.json
```

**Expected behavior**
---
application/octet-stream can streaming instead of receiving the full packet before transmission

**Environment and versions**
---
 - OS:  ```Linux safe-frogs-3.localdomain 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux```

 - cloudflared Version: cloudflared version 2023.6.1 (built 2023-06-20-0926 UTC)
