### ISSUE TITLE
🐛 "cloudflared tunnel run" requires exactly 1 argument, the ID of the tunnel to run.

### ISSUE THREAD

**Issue by boris1993** [cloudflare/cloudflared#1044]
**Describe the bug**
Log says `"cloudflared tunnel run" requires exactly 1 argument, the ID of the tunnel to run.` when running the cloudflared with Docker.

**To Reproduce**
- Create a tunnel in Zero Trust and copy the token from the command sample provided by the wizard.

```
docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token <THE_TUNNEL_TOKEN>
```

- Start the tunnel with this `docker-compose.yml`

```yaml
---
version: '3'

services:
  cloudflare_tunnel_ocr_api:
    image: cloudflare/cloudflared:latest
    restart: always
    container_name: cloudflare_tunnel_ocr_api
    environment:
      - TUNNEL_TOKEN=<THE TUNNEL TOKEN>
      - TZ=Asia/Shanghai
    command: tunnel run
```

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : bf22859e-fe37-4b6e-92cc-64c137543215
5. cloudflared config: N/A. Only the environment variables from the `docker-compose.yml`.

**Expected behavior**
The cloudflared starts successfully.

**Environment and versions**
 - OS: Ubuntu 22.04 LTS
 - Architecture: amd64
 - Version: latest - 865a577bc5cb

**Logs and errors**
Repeats

```text
"cloudflared tunnel run" requires exactly 1 argument, the ID of the tunnel to run.
See 'cloudflared tunnel run --help'.
```

**Additional context**
This configuration works before, but suddenly stopped working from a version which I don't know.
