### ISSUE TITLE
🐛

### ISSUE THREAD

**Issue by ShivamB25** [cloudflare/cloudflared#1064]
**Describe the bug**
I am experiencing an issue with my Cloudflare Tunnel setup, where a service running on port 8080 is accessible locally, but the tunnel is not working as expected. Despite port 8080 being accessible locally, the tunnel does not seem to be correctly forwarding traffic to the local service.

**To Reproduce**
1. Configure Cloudflare Tunnel with the provided configuration
2. Ensure that the local service (e.g., nextjs) is running and listening on port 8080.
3. Attempt to access the service via the Cloudflare Tunnel

If it's an issue with Cloudflare Tunnel:
5. Tunnel ID : 6724a6a4-e147-4692-a058-1f689de16d00
6. cloudflared config: 
```yaml
cloudflared2:
  image: cloudflare/cloudflared:latest
  container_name: cloudflare2
  command:
    - tunnel
    - --no-autoupdate
    - run
    - token
    - {token_2}
  networks:
    - custom_network
  restart_policy:
    condition: on-failure
  restart: unless-stopped
```

**Expected behavior**
I expected that the Cloudflare Tunnel would route traffic from Cloudflare to my local service on port 32400, allowing external access to the service.

**Environment and versions**
 - OS: Ubuntu 22.04.3 LTS
 - Architecture: AMD
 - Version: 22.04

**Logs and errors**
<html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>%

**Additional context**
