### ISSUE TITLE
🐛 ingress rules are validated OK but WRN is shown when tunnel is run

### ISSUE THREAD

**Issue by zstephen** [cloudflare/cloudflared#1081]
**Describe the bug**
when running the below
> cloudflared tunnel run [UUID]

the following error is shown in on screen logs
> WRN No ingress rules were defined in provided config (if any) nor from the cli, cloudflared will return 503 for all incoming HTTP requests

attempts to access the site via a browser result in the same error above being listed each time

no other errors show in the logs

**To Reproduce**
1. Configure zero trust tunnel locally/CLI

[UUID].yml contains the following

```
tunnel: [UUID]
credentials-file: /root/.cloudflared/[UUID].json

ingress:
  - hostname: [subdomain].[domain].au
    service: https://localhost:443
  - service: http_status:404
 ```
when running

> cloudflared tunnel --config [UUID].yml ingress validate

results in..

> Validating rules from [UUID].yml
> OK

3. Run 'cloudflared tunnel run [UUID]'
connection messages display on screen
5. See error

> WRN No ingress rules were defined in provided config (if any) nor from the cli, cloudflared will return 503 for all incoming HTTP requests

**Expected behavior**
tunnel should run without above, website is viewable via browser

**Environment and versions**
 - OS: [Ubuntu 22.04.3 LTS]
 - Architecture: [x64]
 - Version: [GNU/Linux 5.15.0-86-generic x86_64]

**Logs and errors**
shown in context above

**Additional context**
please let me know if additional detail is required

Thanks
