### ISSUE TITLE
💡 Toggle to Enable DNS Refresh/Reconfigure After Disconnect

### ISSUE THREAD

**Issue by Lakr233** [cloudflare/cloudflared#1097]
When a connection becomes saturated and subsequently terminates, it may be necessary to reconfigure the DNS for the tunnel to reconnect. We are encountering issues as described below:

```
argo_1         | 2023-11-02T20:29:48Z INF Lost connection with the edge connIndex=1
argo_1         | 2023-11-02T20:29:48Z INF Unregistered tunnel connection connIndex=1 event=0 ip=198.18.3.87
argo_1         | 2023-11-02T20:29:48Z WRN Serve tunnel error error="connection with edge closed" connIndex=1 event=0 ip=198.18.3.87
argo_1         | 2023-11-02T20:29:48Z INF Retrying connection in up to 1s connIndex=1 event=0 ip=198.18.3.87
argo_1         | 2023-11-02T20:29:49Z WRN Connection terminated error="connection with edge closed" connIndex=1
argo_1         | 2023-11-02T20:30:18Z INF Lost connection with the edge connIndex=1
```

The proxy software acts as a DNS server, returning an IP address like `198.18.3.87` in the example above. With the proxy enabled, a virtual network interface forwards any connection to `198.18.3.87` to the actual address. However, after a disconnection, this address may be reassigned, processing other connections from subsequent requests.

As described, the address that Cloudflare's cloudflared service retrieves is not always available. Following a termination, new connections can no longer be established through the previously acquired address. This is reflected in issues #890 and #376.

Overall, it would be beneficial to have an option to enable features like DNS reconfiguration.

I am aware that such options may pose security concerns, so further investigation is warranted.

**Comment by Lakr233** [comment]
Temporary Workaround: Perform Healthcheck with Reboot

Dockerfile, see https://github.com/Lakr233/cloudflared
```
FROM debian:latest

RUN apt-get update && \
    apt-get install -y curl wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=cloudflare/cloudflared:latest /usr/local/bin/cloudflared /usr/local/bin/cloudflared

ENTRYPOINT ["cloudflared", "--no-autoupdate"]
CMD ["version"]
```

And then configure a healthcheck:
```
version: '3.8'

services:

  argo:
    image: ghcr.io/lakr233/cloudflared:main
    restart: always
    command: tunnel --metrics 0.0.0.0:3333 run --protocol http2  --token **token_string_here**
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3333/ready || exit 1"]
      interval: "5s"
      timeout: "5s"
      retries: "3"
      start_period: "15s"
```
