### ISSUE TITLE
Support setting http Host header

### ISSUE THREAD

**Issue by davidkarlsen** [cloudflare/cloudflared#111]
Support setting 'Host: target' http headers when creating tunnel.

A number of web targets rely on vhost/host matching to properly operate.

**Comment by davebarrau** [comment]
@davidkarlsen Can you check my PR and see if it works for you?

**Comment by davidkarlsen** [comment]
@davebarrau Do you have a binary to run?

**Comment by davebarrau** [comment]
> @davebarrau Do you have a binary to run?

I have a binary I built for Mac.. if you trust random binaries from people on the internet. Better off building it yourself, golang makes it pretty easy. :)

**Comment by davidkarlsen** [comment]
Works like a charm!

**Comment by gajus** [comment]
Is there a way to pass the original Host header?

**Comment by abelinkinbio** [comment]
Hi @gajus - Here is some [documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress#httphostheader) you may find useful on setting httpHostHeader via Ingress Rules in your configuration file. 

If I understand correctly, your configuration file may look something like this: 

```
tunnel: Name of UUID
credentials-file: /root/.cloudflared/UUID.json

ingress:
- hostname: speedtest.example.com
    service: https://speed.cloudflare.com
    originRequest:
      httpHostHeader: speed.cloudflare.com
      noTLSVerify: true
```

Hope this helps.
