### ISSUE TITLE
support protocol relative service url

### ISSUE THREAD

**Issue by realies** [cloudflare/cloudflared#1189]
at the moment config.yml requires the scheme of the internal service to be specified,
this prevents internal services, like reverse proxies, to determine which protocol is used and behave accordingly;
can http and https be supported for a single service? e.g. a protocol-relative URL:

```
tunnel: ***
credentials-file: /home/nonroot/.cloudflared/***.json

ingress:
  - hostname: "*.example.com"
    service: //nginx-proxy-manager

  - service: http_status:404
```
