### ISSUE TITLE
🐛Some HTTP requests are dropped between cloudflare edge and cloudflared

### ISSUE THREAD

**Issue by Javdu10** [cloudflare/cloudflared#1193]
Hello there

**Describe the bug**
Some HTTP requests are dropped between cloudflare proxies and my cloudflared instance
I have a script that do a POST request every minutes and on the machine where the cloudflared is running
(timezone of cloudflare account and server are different hence the 1hour difference)

I ran `cloudflared tail 8eddaaeb-0a19-4106-91d4-13e4aaa44407 | while read line ; do echo "$line" | grep URL ; done`

![image](https://github.com/cloudflare/cloudflared/assets/21960875/7d68e4cc-9e99-4401-a770-e8034359d459)

If you pay attention you can see a 1 minute gap, now the fun part is that I can see the HTTP request in cloudflare WAF event
I am just skipping the "super bot fight mode rule" and logging the requests that "Skip"

![image](https://github.com/cloudflare/cloudflared/assets/21960875/2fe4f7c5-91a9-46ff-a30c-cb51665d1d51)

**To Reproduce**
Unfortunatly I don't have a reproducer because I am still investigating on my server 
Since the version is still supported (2023.8.2), I come here to see if it was a known issue and I can just upgrade 
or if I can get more logs through your guidance to help resolve the issue, please let me know

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 8eddaaeb-0a19-4106-91d4-13e4aaa44407
5. cloudflared config: 
```
tunnel: 8eddaaeb-0a19-4106-91d4-13e4aaa44407
credentials-file: /root/.cloudflared/8eddaaeb-0a19-4106-91d4-13e4aaa44407.json
ingress:
    - hostname: ssh.xxx.yyy
      service: ssh://localhost:22
    - service: https://127.0.0.1:443
      originRequest:
         originServerName: xxx.yyy
```
**Expected behavior**
An error log or that no HTTP requests are dropped

**Environment and versions**
 - OS: Linux
 - Architecture: AMD
 - Version: 2023.8.2

**Additional context**
This behavior seems to happens regularly

I don't know if it's of any use, the Ray-ID of a request that did not make it to my webserver:  85d2fa517df72f4a 

in journalctl I have these logs : 

```
Feb 29 18:19:12 xxx-web cloudflared[146609]: 2024-02-29T17:19:12Z WRN Your version 2023.8.2 is outdated. We recommend upgrading it to 2024.2.1
Feb 29 18:30:36 xxx-web cloudflared[146609]: 2024-02-29T17:30:36Z WRN expected start_streaming as first recieved event
Feb 29 18:30:36 xxx-web cloudflared[146609]: 2024-02-29T17:30:36Z INF
Feb 29 19:16:14 xxx-web cloudflared[146609]: 2024-02-29T18:16:14Z INF Another management session request for the same actor was requested; the other session will be disconnected to handle the new request.
```
