### ISSUE TITLE
💡Ability to authenticate multiple accounts

### ISSUE THREAD

**Issue by adampatterson** [cloudflare/cloudflared#1238]
**Describe the feature you'd like**
If a tunnel is used for local development there is the potential that a developer would require a different authentication for Personal or Work.

**Describe alternatives you've considered**
I'd like to run one at a time, never both at once.

`cloudflared tunnel run personal`

`cloudflared tunnel run work`

```yml
tunnels:
  - tunnel: personal
    credentials-file: /root/.cloudflared/personal.json
    cert: /root/.cloudflared/personal.pem
    ingress:
      - hostname: "*.personal.dev"
        service: http://127.0.0.1:80
      - service: http_status:404
  - tunnel: work
    credentials-file: /root/.cloudflared/work.json
    cert: /root/.cloudflared/work.pem
    ingress:
      - hostname: "*.work.dev"
        service: http://127.0.0.1:80
      - service: http_status:404
```

As far as I could tell this isn't possible.
