### ISSUE TITLE
💡Add docker healthcheck

### ISSUE THREAD

**Issue by juma-allan** [cloudflare/cloudflared#1268]
**Describe the feature you'd like**
A clear and concise description of the feature. What problem does it solve for you?

A healthcheck would enable us to programatically restart the container incase of any failure

**Comment by ssqlone** [comment]
Try this:
```
    healthcheck:
      test: ["CMD", "cloudflared", "version"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
```
