### ISSUE TITLE
🐛 Page with websockets renders blank

### ISSUE THREAD

**Issue by jongio** [cloudflare/cloudflared#1272]
**Describe the bug**
I have a webpage that uses ws, wss, and http and it doesn't render anything.

**To Reproduce**

Create config:
```
tunnel: 
credentials-file: 

ingress:
  - hostname: hostname
    service: https://localhost:7292
  - service: http_status:404
 ```
Start the tunnel

Hit the page on public domain

You will see requests for ws://localhost:port, wss://localhost:/post, and http:requests.

How do I configure cloudflared to work in this setup?  I have tried originRequest/httpHostHeader setting to localhost.

**Expected behavior**
Page renders

**Environment and versions**
 - OS: [e.g. MacOS]  Windows
 - Architecture: [e.g. AMD, ARM]
 - Version: [e.g. 2022.02.0]

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**
