### ISSUE TITLE
🐛 Websocket timeout when upgrading insequre ws request to use wss

### ISSUE THREAD

**Issue by nooisy** [cloudflare/cloudflared#1306]
**Describe the bug**
I'm trying to remotely access a [Bela device ](https://github.com/BelaPlatform/Bela). A webpage can be accessed on port 80 and certain parts of the webpage need a websocket connection (:5555) page to render. Locally the whole page works but remotely the websocket part fails to load. Firefox console gives me: 
- HTTPS-Only Mode: Upgrading insecure request “ws://bela.domain.app:5555/gui_data” to use “wss”.
- Firefox can’t establish a connection to the server at wss://bela.domain.app:5555/gui_data.

My config.yaml looks like this:
```
url: http://localhost:80
tunnel:
credentials-file:
ingress:
  - hostname: bela.domain.app
    service: http://localhost:80
  - hostname: bela.domain.app
    service: ws://localhost:5555
  - service: http_status:404
```
