### ISSUE TITLE
📝 Documentation for using kubectl to access remote K8s API Server using Cloudflare Products

### ISSUE THREAD

**Issue by abasu0713** [cloudflare/cloudflared#1388]
**Available Documentation**
1. https://developers.cloudflare.com/cloudflare-one/tutorials/kubectl/
2. https://developers.cloudflare.com/cloudflare-one/tutorials/tunnel-kubectl/

**Suggested Documentation**
The documentation for using `kubectl` through SOCKs proxy is completely outdated. The [blog post](https://blog.cloudflare.com/releasing-kubectl-support-in-access/) and documentation [1] is very misleading. I have spent over 2 days trying to get it working - to no avail. I get Handshake Errors, Certificate Errors, and so many other things. It just doesn't work. 

The documentation for using `kubectl` with __Kubernetes client-go__ is also very incomplete. The [Step - 2: Configure k8s API Server](https://developers.cloudflare.com/cloudflare-one/tutorials/tunnel-kubectl/#2-configure-the-kubernetes-api-server) is also very incomplete. Could someone provide some detailed steps on how to do that?

**Comment by abasu0713** [comment]
any updates on this?

**Comment by andres-ortiz** [comment]
Hello,

After reviewing the client-go portion with a friend, we noticed that kubectl sends an “Authorization: Bearer ” header, while Cloudflare Access expects a different type of header for authentication and traffic allowance. I’m not sure how the tutorial can work without additional information.

**Comment by abasu0713** [comment]
> Hello,
> 
> After reviewing the client-go portion with a friend, we noticed that kubectl sends an “Authorization: Bearer ” header, while Cloudflare Access expects a different type of header for authentication and traffic allowance. I’m not sure how the tutorial can work without additional information.

I figured it out. And was able to fix it. It required regenerating the cluster certificates with the DNS value i use for Cloudflare proxy. I will write out a blog for the detailed steps and share here.

**Comment by Surya-bbas** [comment]
@abasu0713  where you able to write this blog ?, pls share some ref.

**Comment by ShawnDen-coder** [comment]
```yaml
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: "*.example.com"
      recordType: CNAME
      targets: ["1b66b6d3-c456-4cf4-9d1b-7ef103be0ed4.cfargotunnel.com"]
---
replica:
  allNodes: true
  count: 2
tunnelConfig:
  name: homelab-cluster
  connectTimeout: 60s
ingress:
  - hostname: 'cluster.example.com'
    service: https://192.168.31.117:16443  # i use microk8s
    originRequest:
      noTLSVerify: true
  - hostname: '*.example.com'
    service: https://192.168.31.100 # my ingress ip
    originRequest:
      noTLSVerify: true
  - service: http_status:404
```

When I used it this way, Cloudflare did not create a new Public hostname: 'cluster.example.com'. Also, there was a 509 validation error. 

I started the Cloudflare tunnel on the cluster using the helm image from https://artifacthub.io/packages/helm/community-charts/cloudflared.
