### ISSUE TITLE
🐛

### ISSUE THREAD

**Issue by hitoyaCute** [cloudflare/cloudflared#1473]
**Describe the bug**
I don't have the definite conclusion on how it happens but i cant access the tunnel, what i'm doing is to create a ssh tunnel for me server. login it on my other device gives no result, just blank

**To Reproduce**
Installation: i use the CLI Ubuntu installation instruction
Run
```console
$ cloudflared tunnel run my_tunnel
```

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 1ab6cbf4-4cfd-477f-9e63-894b73ffdbb1
5. cloudflared config: 
```yml
tunnel:<Tunnel-ID>
credentials-file: <Credentials-file-dir>

ingress:
  - hostname: <My-Host-Name>
    service: ssh://localhost:22

  - service: http_status:404
```

**Environment and versions**
 - OS: Ubuntu server
 - Architecture: x86_64
 - Device: acer Travel-mate 5730 (maybe its hardware issue... i have no idea)

**Additional context**
i also tried it on other system on same device however it behaves same exact thing, even giving same exact output
just say if any information is needed to solve this issue
