### ISSUE TITLE
h2mux handshake with edge error

### ISSUE THREAD

**Issue by xUnholy** [cloudflare/cloudflared#203]
I'm attempting to use argo tunnel in the sidecar kubernetes approach as explained here: https://developers.cloudflare.com/argo-tunnel/reference/sidecar/ 

https://github.com/cloudflare/cloudflared/blob/fbe2989f61fcdcecc4062b6c10cdabb571a6d6d7/origin/tunnel.go#L600

I'm coming across a strange issue when trying to create the tunnel as shown below:

```
❯ k logs hello-69464c85c9-9ql2j -c tunnel -f
time="2020-05-27T08:34:54Z" level=warning msg="Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /usr/local/etc/cloudflared /etc/cloudflared]"
time="2020-05-27T08:34:54Z" level=warning msg="At debug level, request URL, method, protocol, content legnth and header will be logged. Response status, content length and header will also be logged in debug level."
time="2020-05-27T08:34:54Z" level=info msg="Version 2020.5.1-6-ga908453"
time="2020-05-27T08:34:54Z" level=info msg="GOOS: linux, GOVersion: go1.14.3, GoArch: arm64"
time="2020-05-27T08:34:54Z" level=info msg=Flags hostname=hello.raspbernetes.com loglevel=debug no-autoupdate=true origincert=/etc/cloudflared/cert.pem proxy-dns-upstream="https://1.1.1.1/dns-query, https://1.0.0.1/dns-query" url="http://127.0.0.1:8080"
time="2020-05-27T08:34:55Z" level=debug msg="Reading origin cert from /etc/cloudflared/cert.pem"
time="2020-05-27T08:34:55Z" level=info msg="Starting metrics server" addr="127.0.0.1:46273/metrics"
time="2020-05-27T08:35:16Z" level=info msg="Proxying tunnel requests to http://127.0.0.1:8080"
time="2020-05-27T08:35:18Z" level=debug msg="Giving connection its new address 198.41.200.193:7844" connID=0 function=GetAddr subsystem=edgediscovery
time="2020-05-27T08:35:32Z" level=error msg="Tunnel creation failure" connectionID=0 error="h2mux handshake with edge error: Handshake error: 1000 handshake timeout"
time="2020-05-27T08:35:32Z" level=info msg="Initiating graceful shutdown due to h2mux handshake with edge error: Handshake error: 1000 handshake timeout ..."
time="2020-05-27T08:35:32Z" level=error msg="Quitting due to error" error="h2mux handshake with edge error: Handshake error: 1000 handshake timeout"
time="2020-05-27T08:35:32Z" level=info msg="Metrics server stopped"
h2mux handshake with edge error: Handshake error: 1000 handshake timeout
```

My configuration is a literal copy/paste from the demonstration however, I'll post it in case I'm missing something?

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: raspbernetes/custom-error-pages
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 40Mi
            requests:
              cpu: 20m
              memory: 40Mi
        - name: tunnel
          image: raspbernetes/cloudflared:2020.5.1
          imagePullPolicy: Always
          command: ['cloudflared', 'tunnel']
          args:
            - --url=http://127.0.0.1:8080
            - --hostname=hello.raspbernetes.com
            - --origincert=/etc/cloudflared/cert.pem
            - --no-autoupdate
            - --origin-server-name raspbernetes.com
            - --loglevel=debug
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /etc/cloudflared
              name: tunnel-secret
              readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: tunnel-secret
          secret:
            secretName: raspbernetes.com-cloudflared-cert
```

**Comment by xUnholy** [comment]
I've raised an issue in the community and has some support with no success here: https://community.cloudflare.com/t/argo-tunnel-kubernetes-sidecar-model/169342/4

**Comment by xUnholy** [comment]
Applied more to the logging

```
        - name: tunnel
          image: raspbernetes/cloudflared:2020.5.1
          imagePullPolicy: IfNotPresent
          command: ['cloudflared', 'tunnel']
          args:
            - --url=http://127.0.0.1:8080
            - --hostname=hello.raspbernetes.com
            - --origincert=/etc/cloudflared/cert.pem
            - --no-autoupdate
            - --origin-server-name=raspbernetes.com
            - --loglevel=debug
            - --proto-loglevel=warn
            - --retries=8
```

Got the following logs:

```
❯ k logs echo-647d594776-ntj86 -c tunnel -f
time="2020-05-27T09:14:09Z" level=warning msg="Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /usr/local/etc/cloudflared /etc/cloudflared]"
time="2020-05-27T09:14:09Z" level=warning msg="At debug level, request URL, method, protocol, content legnth and header will be logged. Response status, content length and header will also be logged in debug level."
time="2020-05-27T09:14:10Z" level=info msg="Version 2020.5.1-6-ga908453"
time="2020-05-27T09:14:10Z" level=info msg="GOOS: linux, GOVersion: go1.14.3, GoArch: arm64"
time="2020-05-27T09:14:10Z" level=info msg=Flags hostname=hello.raspbernetes.com loglevel=debug no-autoupdate=true origin-server-name=raspbernetes.com origincert=/etc/cloudflared/cert.pem proto-loglevel=warn proxy-dns-upstream="https://1.1.1.1/dns-query, https://1.0.0.1/dns-query" retries=8 transport-loglevel=warn url="http://127.0.0.1:8080"
time="2020-05-27T09:14:12Z" level=info msg="Starting metrics server" addr="127.0.0.1:36057/metrics"
time="2020-05-27T09:14:12Z" level=debug msg="Reading origin cert from /etc/cloudflared/cert.pem"
time="2020-05-27T09:14:36Z" level=info msg="Proxying tunnel requests to http://127.0.0.1:8080"
time="2020-05-27T09:14:39Z" level=debug msg="Giving connection its new address 198.41.200.193:7844" connID=0 function=GetAddr subsystem=edgediscovery
time="2020-05-27T09:14:50Z" level=error msg="Tunnel creation failure" connectionID=0 error="h2mux handshake with edge error: read tcp 10.32.0.8:38346->198.41.200.193:7844: read: connection reset by peer"
time="2020-05-27T09:14:50Z" level=info msg="Initiating graceful shutdown due to h2mux handshake with edge error: read tcp 10.32.0.8:38346->198.41.200.193:7844: read: connection reset by peer ..."
time="2020-05-27T09:14:50Z" level=info msg="Metrics server stopped"
time="2020-05-27T09:14:50Z" level=error msg="Quitting due to error" error="h2mux handshake with edge error: read tcp 10.32.0.8:38346->198.41.200.193:7844: read: connection reset by peer"
h2mux handshake with edge error: read tcp 10.32.0.8:38346->198.41.200.193:7844: read: connection reset by peer
```
