### ISSUE TITLE
Expose readiness / healthcheck endpoint for the tunnel

### ISSUE THREAD

**Issue by IljaDaderko** [cloudflare/cloudflared#204]
I am using cloudflared tunnel via a docker container in kubernetes. It is deployed in sidecar manner along with 2 other containers (making total container size in a pod of 3). I have `livenessProbe` and `readinessProbe` set up for other 2 containers that just ping `/healthz` path. I wasn't able to find proper mechanism to add this to my cloudflared tunnel container. This leads to pod being in "Ready" with `2/3` containers. Which is not ideal. Is there something I could utilise for cloudflared tunnel or perhaps something should be added?

**Comment by HofmannZ** [comment]
@IljaDaderko Can you perhaps share your solution? We're facing the same issue ;)

**Comment by mtmn** [comment]
+1 on this one.

**Comment by SupremeTechnopriest** [comment]
We would like something local to the container as well.  Currently we are solving the problem by `wget` to the tunnel url but it's less than ideal because it has to go out to the internet.  We set it in a really slow interval and it takes a long time for the container to show green.  If we could hit something local to the container that would be ideal.  We aren't using `cloudflared tunnel create` so `cloudflared tunnel list` is out of the question.

```yaml
          livenessProbe:
            exec:
              command:
                - wget 
                - -q 
                - --spider 
                - https://thetunnelurl.com
            initialDelaySeconds: 120
            periodSeconds: 900
          readinessProbe:
            exec:
              command:
                - wget
                - -q 
                - --spider 
                - https://thetunnelurl.com
```

**Comment by HofmannZ** [comment]
You can check the readiness endpoint of the `cloudlfared` metrics server. It is available at `/ready`. 

```yaml
name: tunnel
image: docker.io/cloudflare/cloudflared:2020.12.0
imagePullPolicy: Always
command:
- cloudflared
- tunnel
args:
- --url=http://127.0.0.1:3000
- --hostname=example.com
- --origincert=/etc/cloudflared/cert.pem
- --lb-pool=example-pool
- --metrics=localhost:3333
- --no-autoupdate
env:
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
volumeMounts:
- mountPath: /etc/cloudflared
  name: tunnel-secret
  readOnly: true
livenessProbe:
  httpGet:
    path: /ready
    port: 3333
    scheme: HTTP
  initialDelaySeconds: 120
readinessProbe:
  httpGet:
    path: /ready
    port: 3333
    scheme: HTTP
  initialDelaySeconds: 120
```

If you're running k8s 1.18 or higher you should be able to use a `startupProbe` and remove the `initialDelaySeconds` from the `livenessProbe` and `readinessProbe`.

```yaml
...

livenessProbe:
  httpGet:
    path: /ready
    port: 3333
    scheme: HTTP
readinessProbe:
  httpGet:
    path: /ready
    port: 3333
    scheme: HTTP
startupProbe:
  httpGet:
    path: /ready
    port: 3333
    scheme: HTTP
  failureThreshold: 60
  periodSeconds: 10
```
