### ISSUE TITLE
Difficulty proxing multiple services with argo tunnel.

### ISSUE THREAD

**Issue by anuraagrijal3138** [cloudflare/cloudflared#272]
I am trying to test proxing multiple services with argo tunnel using CNAME record referencing the docs. 
https://developers.cloudflare.com/argo-tunnel/configuration/ingress
I am trying to use ingress rule to expose my services. My config looks like following:
```
tunnel: e8ed6823-b251-411b-a2e6-xxxxxxxxxxxx
credentials-file: /home/anuraag/.cloudflared/e8ed6823-b251-411b-a2e6-xxxxxxxxxxxx.json

ingress:
  - hostname: anuraag-pc.aib.work
    service: http://localhost:80
  - hostname: anuraag-pc-ssh.aib.work
    service: ssh://localhost:22
  - service: http_status:404
```
My question is where should I create entries for anuraag-pc.aib.work and anuraag-pc-ssh.aib.work to access these services externally? For example, How do I ssh into the server where this cloudflared instance is running? 
Right now I have created them in Cloudflare Access tab. I have also created CNAME record for e8ed6823-b251-411b-a2e6-xxxxxxxxxxxx.cfargotunnel.com.

I have the latest version of cloudflared. 
cloudflared version 2020.11.11 (built 2020-11-25-1643 UTC)

Please close the issue if this is not the right place for this kind of question. Thank you.
