### ISSUE TITLE
Any plan for a Cloudflare WARP client for Linux

### ISSUE THREAD

**Issue by balupton** [cloudflare/cloudflared#284]
As the current `cloudflared` setup is too complicated or incomplete:

1. I do `cloudflare login` which creates the `pem` file
2. Then run `sudo cloudflared service install` but complains there is no config file, so I create one with:
   ``` yaml
    proxy-dns: true
    proxy-dns-upstream:
    - one of the dns settings for the location from the teams dashboard
    - one of the dns settings for the location from the teams dashboard
    - one of the dns settings for the location from the teams dashboard
    ```
4. But then `sudo cloudflared service install` complains that:
    ```
    Configuration file /usr/local/etc/cloudflared/config.yml must contain entries for the tunnel to run and its associated credentials:
    tunnel: TUNNEL-UUID
    credentials-file: CREDENTIALS-FILE
    ```
    in which case, what was the point of `cloudflare login`?

I just want to be able to install warp on my server, authenticate, then have my tunnels setup via the dashboard.
