### ISSUE TITLE
Route to https service

### ISSUE THREAD

**Issue by anuraagrijal3138** [cloudflare/cloudflared#294]
I am trying to create an argo tunnel that exposes kubernetes api server. I am following:
https://developers.cloudflare.com/access/other-protocols/kubectl

But I want to do it with config file and ingress.
I have the following config file.
```
tunnel: 79842681-fe04-4f01-bd9a-xgxgxgxg
credentials-file: /etc/cloudflared/tunnel-credentials.json
ingress:
-  hostname: kubectl.test-dd-eks-cluster-1.abc.work
   service: tcp://kubernetes.default:443
   proxyType: socks
```
This way I can reach the api server, but I have to do it via:
```
cloudflared access tcp --hostname kubectl-test-dd-eks-cluster-1.abc.work --url 127.0.0.1:1234
```
I tried to use "service: https://kubernetes.default:443" in config file so that I can put "https://kubectl.test-dd-eks-cluster-1.abc.work" in the server field in the kubeconfig but it did not work.

Can we use https service in the service field of the config? Is there any docs on how to access kube apiserver via argo tunnel the new way?

Thank you!

**Comment by chungthuang** [comment]
Hi @anuraagrijal3138, yes you can put https service in the service field. The proxyType setting has to be put under the `originRequest` key, so something like
```
ingress:
-  hostname: kubectl.test-dd-eks-cluster-1.abc.work
   service: https://kubernetes.default:443
   originRequest:
     proxyType: socks
     caPool: <path-to-kubeapi-ca>
```
Based on my experience you will also need to specify the CA file of your kubeapi. 
The documentation for the config file is in https://developers.cloudflare.com/argo-tunnel/configuration/ingress#origin-configurations.

**Comment by anuraagrijal3138** [comment]
Hello @chungthuang Thank you for the reply. I have changed my config file and everything seems to work fine now. 
One thing that I had to change was use "insecure-skip-tls-verify: true" in client kubeconfig rather than "certificate-authority-data:". I was getting cert signed by unknown authority error because the tunnel URL is not approved server name in EKS. In this case the authentication is done in the cloudflared tunnel pod using "/etc/cloudflared/apiserver-ca-cert.pem".
```
ingress:
- hostname: kubectl-test-dd-eks-cluster-3.aib.work
  service: https://kubernetes.default:443
  originRequest:
    proxyType: socks
    caPool: /etc/cloudflared/apiserver-ca-cert.pem
```
