### ISSUE TITLE
Support all configuration fields as cli and/or environment variables

### ISSUE THREAD

**Issue by jmonson** [cloudflare/cloudflared#303]
We would like deploy cloudflared in Kubernetes using purely environment variables directly for configuration (versus writing to a file). 

Example:
```
apiVersion: v1
kind: Pod
metadata:
  name: cloudflared
spec:
  containers:
  - name: cloudflared
    image: cloudflare/cloudflared
   command:  ["tunnel","--ingress","'service:myservice,hostname:myhost'","--tunnelSecret","$TUNNEL_SECRET","run","$TUNNEL_NAME"]
    env:
      - name: TUNNEL_ACCOUNT_TAG
        valueFrom:
          secretKeyRef:
            name: cloudflared
            key: accountTag
      - name: TUNNEL_SECRET
        valueFrom:
          secretKeyRef:
            name: cloudflared
            key: tunnelSecret
      - name: TUNNEL_ID
        valueFrom:
          secretKeyRef:
            name: cloudflared
            key: tunnelId
      - name: TUNNEL_NAME
        valueFrom:
          secretKeyRef:
            name: cloudflared
            key: tunnelName
```
