### ISSUE TITLE
tag argument = expected string slice found string for tag

### ISSUE THREAD

**Issue by centminmod** [cloudflare/cloudflared#312]
Does the tag argument work in config.yml https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/arguments#--tag ?

I tried in config.yml

```
tag: cmm=test
```

and get

```
cloudflared tunnel --config ~/.cloudflared/config.yml run tun.domain.com
expected string slice found string for tag
```

```
cloudflared --version
cloudflared version 2021.2.1 (built 2021-02-04-1528 UTC)
```

**Comment by adamchalmers** [comment]
Hi there, the `tag` doesn't do anything currently, it was originally added to Argo Tunnel in its early testing/development phase and we haven't wanted to remove it for backwards compatibility reasons.

**Comment by centminmod** [comment]
thanks @adamchalmers  for the clarification 

I did find git repo tags are formatted differently in config.yml example at https://github.com/cloudflare/cloudflared/blob/master/cmd/cloudflared/config/configuration_test.go#L36-L38 compared to https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/arguments#--tag

```
tunnel: config-file-test
ingress:
 - hostname: tunnel1.example.com
   path: /id
   service: https://localhost:8000
 - hostname: "*"
   service: https://localhost:8001
retries: 5
grace-period: 30s
percentage: 3.14
hostname: example.com
tag:
 - test
 - central-1
counters:
 - 123
 - 456
```
