### ISSUE TITLE
Proxying paths for a HTTP service

### ISSUE THREAD

**Issue by samloh84** [cloudflare/cloudflared#331]
Hi,

I have the following config.yaml configuration, running cloudflared 2021.2.5:

```
tunnel: my-named-tunnel
credentials-file: /my-username/.cloudflared/tunnel-uuid.json
origincert: /my-username/.cloudflared/cert.pem

ingress:
  - hostname: subdomain.rootdomain.com
    service: http://nginx.mynetwork.com
  - service: http_status:404
```

It seems that all paths are being matched in the ingress rule above, so even the assets referenced in index.html are all copies of index.html. E.g, if my index.html is the following:
```
<html><body><img src="image.png"/></body></html>
```
Navigating to `https://subdomain.rootdomain.com/image.png` gives me the above html content again.

Is there some configuration that I am missing that proxies paths to the http service?

Thanks and regards.
