### ISSUE TITLE
Ingress configuration doesn't work with proxy dns

### ISSUE THREAD

**Issue by daxxog** [cloudflare/cloudflared#346]
This configuration does not work:
```
tunnel: {{MY_TUNNEL_ID}}
credentials-file: {{MY_CREDENTIALS_FILE}}


ingress:
  - hostname: {{MY_HOSTNAME}}
    service: {{MY_SERVICE_URL}}
    originRequest:
      httpHostHeader: {{MY_HTTP_HOST_HEADER}}
  # Catch-all rule, which just responds with 404 if traffic doesn't match any of
  # the earlier rules
  - service: http_status:404


loglevel: debug
logfile: /var/log/cloudflared.log
proxy-dns: true
proxy-dns-port: 9053
```

However, if I comment out:
```
# proxy-dns: true
# proxy-dns-port: 9053
```

Then everything works fine.
