### ISSUE TITLE
ErrorProxying to ingress 0 error: Error proxying request to origin: dial tcp 172.20.0.3:80: i/o timeout

### ISSUE THREAD

**Issue by ralgar** [cloudflare/cloudflared#363]
I am trying to connect cloudflare/cloudflared container to linuxserver/swag (nginx) container but getting an error.

Yaml configuration:
```
ingress:
  - hostname: redacted.com
    service: http://swag:80
  # Catch-all rule
  - service: http_status:404
```

Error:
`2021-04-30T05:41:59Z ERR CF-RAY: 647e70fbce11ecfa-YUL Proxying to ingress 0 error: Error proxying request to origin: dial tcp 172.20.0.3:80: i/o timeout`

There is nothing in the logs of the nginx container.
