### ISSUE TITLE
Unable to use cloudflared docker image to run tunnel without cert.pem

### ISSUE THREAD

**Issue by thanatchakromsang** [cloudflare/cloudflared#409]
When installing cloudflared binary in docker manually or Install directly on a machine I can run `cloudflared tunnel run` without `cloudflared tunnel login` or `cert.pem` but not when using `cloudflared/cloudflared` images It keeps asking for `cert.pem` even though it possible to run without `cert.pem` following this guideline https://developers.cloudflare.com/cloudflare-one/tutorials/credentials-only

Docker-compose example

```yaml
services:
  cloudflared:
    image: cloudflare/cloudflared:2021.6.0
    volumes:
      - ./credential.json:/etc/cloudflared/credential.json
      - ./config.yaml:/etc/cloudflared/config.yaml
    entrypoint:
      - cloudflared
    command:
      - tunnel
      - run
    restart: unless-stopped
```

credential.json

```json
{
  "AccountTag": "redacted",
  "TunnelSecret": "redacted",
  "TunnelID": "redacted",
  "TunnelName": "redacted"
}
```

config.yaml

```yaml
tunnel: redacted
credentials-file: "/etc/cloudflared/credential.json"

ingress:
  - hostname: subdomain.domain.com
    service: http://localhost:3000
  - service: http_status:404
```

![image](https://user-images.githubusercontent.com/25862154/124710274-bc8c6180-df26-11eb-88db-7348d62c6951.png)
