### ISSUE TITLE
can i user cloudflared to proxy my local netwrok server 

### ISSUE THREAD

**Issue by fengzhao** [cloudflare/cloudflared#424]
I want to use cloudflard like blow , not localhost, but other local network ip address instead

```
tunnel: 6ff42ae2-765d-4adf-8112-31c55c1551ef
credentials-file: /root/.cloudflared/6ff42ae2-765d-4adf-8112-31c55c1551ef.json

ingress:
  - hostname: gitlab.widgetcorp.tech
    service: http://my-local-network-ip:80
  - hostname: gitlab-ssh.widgetcorp.tech
    service: ssh://localhost:22
  - service: http_status:404
```
