### ISSUE TITLE
[Question] Multiple service endpoints for a single hostname 

### ISSUE THREAD

**Issue by teh-random-name** [cloudflare/cloudflared#434]
I want to expose a load balanced web application via Cloudflared but I can't find anything in the documentation regarding this style of configuration without running multiple instances of Cloudflared.

This is more of a sanity check but is it possible to provide multiple `service` entries for a single `hostname` entry in the config yaml?

Something like the following:
```yaml
ingress:
  - hostname: service.domain.com
   service: 
      - http://backend-01.lan
      - http://backend-02.lan
      - http://backend-03.lan
```
