### ISSUE TITLE
Accessing TCP/non-HTTP services w/o Cloudflare Access?

### ISSUE THREAD

**Issue by SStorm** [cloudflare/cloudflared#489]
Hi there, 

we've been successfully using ARGO/cloudflared to tunnel things to internal HTTP servers, with a `tunnel.yaml` looking something like this:
```
tunnel: [my-tunnel-id]
credentials-file: /etc/cloudflared/tunnel.json

ingress:
- hostname: some-subdomain.example.com
  service: http://my-http-service
- service: http://my-http-service
```

I can go to `https://some-subdomain.example.com` in the browser and it proxies just fine.

Now we'd like to also expose an arbitrary TCP service in this way. `cloudflared` [docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress#supported-protocols) seem to suggest that this is supported, i.e. with something like this:

```
tunnel: [my-tunnel-id]
credentials-file: /etc/cloudflared/tunnel.json

ingress:
- hostname: some-subdomain.example.com
  service: http://my-http-service
- hostname: my-tcp-service.example.com
  service: tcp://some-service:1234
- service: http://my-http-service
```

Should I be able to connect to `my-tcp-service.example.com:1234`? That doesn't seem to work, and the documentation is a bit ambivalent. 

Appreciate your help!
