### ISSUE TITLE
It seems impossible to use cloudflared tunnels to access an internal Docker Registry

### ISSUE THREAD

**Issue by DavidZidar** [cloudflare/cloudflared#500]
For some reason the Docker client requires `Content-Length` headers but these are stripped somewhere in the cloudflared tunnel which makes the docker CLI report the following error:

```
> docker pull myregistry.domain.tld/image:tag
Error response from daemon: missing or empty Content-Length header
```

I have verified using Firefox and the `Content-Length` header is indeed missing.

In trying to work around this issue I have tried to proxy via nginx and add a `Cacne-Control: no-transform` header to no avail. I have also tried using `​proxyType: socks` but it makes little difference, but I may be misusing the feature because I don't understand it.

Is there anything else I can try?

**Comment by nmldiegues** [comment]
I've run a docker registry behind a Cloudflare Tunnel successfully.

Steps on the server/origin machine:
1.  Set up your registry as you wish (I assume it is available on origin machine at localhost:5000)
2. `cloudflared tunnel create docker-registry`
3. `cloudflared tunnel route dns docker-registry my-docker.mydomain.com`
4. `cloudflared tunnel --url http://localhost:5000 run docker-registry` --- you could use ingress rules, I'm just simplifying here

Steps on the machine accessing:
1. `docker pull my-docker.mydomain.com/myimage:version`

And it worked fine.

**Comment by DavidZidar** [comment]
@nmldiegues Interesting, that's more or less exactly what I'm trying to do yet it doesn't work because Docker is refusing to pull anything because the `Content-Length` header is missing. The same registry is working fine if a punch a hole in my firewall.

Potential differences:
* I am using HTTPS using a Cloudflare origin certificate
* The registry is not on the same machine as the tunnel
* I am tunneling more than one service so I'm using an ingress rule

```yml
ingress:
  - hostname: myregistry.domain.tld
    service: https://internal-server.domain.tld:15443
    originRequest:
      httpHostHeader: myregistry.domain.tld
      originServerName: myregistry.domain.tld
```

**Comment by nmldiegues** [comment]
Which cloudflared version are you using?

What's your full config YAML?

**Comment by DavidZidar** [comment]
@nmldiegues cloudflared version 2021.10.5 (built 2021-10-25-1945 UTC)

```yml
tunnel: [uuid]

ingress:

  - hostname: otherservice.domain.se
    service: https://server1.ad.steamcore.se
    originRequest:
      httpHostHeader: otherservice.domain.se
      originServerName: otherservice.domain.se

  - hostname: registry.domain.se
    service: https://server2.ad.steamcore.se:15443
    originRequest:
      httpHostHeader: registry.domain.se
      originServerName: registry.domain.se
      proxyType: socks # I've tried with and without this

  - service: http_status:404
```

I can't run a tunnel on the server with the registry as it's a Synology DiskStation, so what I'm trying to do is to run the tunnel on an ingress server and proxy the traffic to the Synology.
