### ISSUE TITLE
[Feature Request] Possibility to control the scheme, when using Ingress unix sockets

### ISSUE THREAD

**Issue by DavidOsipov** [cloudflare/cloudflared#502]
Dear developers,

Referring [to thread at the Cloudflare Community](https://community.cloudflare.com/t/tunnel-unix-sockets-and-tls-handshakes), I would like to request a feature - a possibility to control the scheme (HTTP or HTTPS), when using Unix domain sockets with the Cloudflare Tunnel.

<h2>Desired behavior:</h2>

Select HTTP or HTTPS for requests from the Cloudflare Tunnel via a Unix domain socket.

When the HTTP scheme selected, the behavior should be smt like this:

<details><summary>Click to expand the picture</summary>

![scheme](https://user-images.githubusercontent.com/38164582/140654711-3a678b86-41d8-4418-b8ea-54a4a44ccd56.jpg)

</details>

<h2>Possible implementation:</h2>

Having config like this should switch the traffic scheme to HTTP, that would be transferred via a Unix domain socket:  
```
protocol: quic
tunnel: sometunnelID
credentials-file: /dir/credentialsfile.json

ingress:
  - hostname: somename
    service: http+unix:/run/somedir/socket.sock
  - service: http_status:404
```

Having config like this should switch the traffic scheme to HTTPS, that would be transferred via a Unix domain socket:  
```
protocol: quic
tunnel: sometunnelID
credentials-file: /dir/credentialsfile.json

ingress:
  - hostname: somename
    service: https+unix:/run/somedir/socket.sock
  - service: http_status:404
```

<h2>Implications:</h2>

The possibility to strip TLS layer from HTTPS, when communication via a Unix domain socket, can introduce performance benefits, such as there would be no need to do a TLS handshakes (reducing latency) and a CPU won't need to spend time encrypting and decrypting a TLS layer (reducing CPU usage). Most probably, the improvements would be much higher on high load servers.

<h2>Possible complications:</h2>

HTTP/1.1 can be transferred without a TLS layer without any problems and modifications. HTTP/2 can be transferred without TLS layer (h2c), but not many clients support it, and webservers like Nginx should be configured to work with it:

```
server {
    listen 443 h2c;
    ...
}
```

But currently and probably in the future, Cloudflare **won't support** HTTP/2 when communicating to an Origin server.
