### ISSUE TITLE
Strange issue with cloudflared tunnel create not detecting cert.pem, but tunnel login does!

### ISSUE THREAD

**Issue by haneef95** [cloudflare/cloudflared#504]
Hi,

I'm facing this strange issue here. Whereby, when I run `tunnel login`, it detects the existing `cert.pem`:
```
$ docker-compose run d tunnel login
You have an existing certificate at /home/nonroot/.cloudflared/cert.pem which login would overwrite.
If this is intentional, please move or delete that file then run this command again.
```

However, when I run `tunnel create`, it cannot find the certificate path:
```
$ docker-compose run d tunnel create my-tunnel
2021-11-09T13:15:52Z INF Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared] originCertPath=
2021-11-09T13:15:52Z ERR You need to specify the origin certificate path with --origincert option, or set TUNNEL_ORIGIN_CERT environment variable. See https://developers.cloudflare.com/argo-tunnel/reference/arguments/ for more information. originCertPath=
failed to create tunnel: couldn't create client to talk to Cloudflare Tunnel backend: Error locating origin cert: client didn't specify origincert path when running from terminal

```

Any suggestions for a fix?

Thanks,

**Comment by haneef95** [comment]
docker image: `cloudflare/cloudflared:2021.11.0-amd64`

**Comment by BrodyStone21** [comment]
I'm experiencing the same issue. I think that what's happening is that the `cert.pem` file is never actually being created. I bet it's some kind of permission issue. I've tried several things and haven't been able to get it to work.

**Comment by abelinkinbio** [comment]
You should be able to quickly see if the `cert.pem` is generated and stored during the login command by checking the `~./.cloudflared` directory.

**Comment by BrodyStone21** [comment]
It's not unfortunately.

**Comment by abelinkinbio** [comment]
Does that also mean when you run  `cloudflared tunnel login` this command hangs?

**Comment by haneef95** [comment]
I managed to fix this actually, it currently works with this:
`docker-compose.yml`:
```
version: "2.4"

services:
    cloudfd:
        image: cloudflare/cloudflared:2021.11.0-amd64
        restart: always
        command: tunnel run
        scale: 2                # Restart is requied after config updates, and takes approx 30, during when all the services are down!
                                # hence, restart seperately.
                                # Supported natively: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/deploy-cloudflared-replicas
        volumes:
            - ./config:/home/nonroot/.cloudflared
              # Cloudflared doesn't seem to have any unattended data that needs persistence, just admin-side config which are fed to it.
              # Hence, the volume will stay within the git.
              #    - ./_data # nowhere to point this to (yet), the folder on the host is there as a placeholder.
```

The local folder `./config` that is mounted all has permissions to `1000:1000`

**Comment by haneef95** [comment]
I managed to fix this actually, it currently works with this:
`docker-compose.yml`:
```
version: "2.4"

services:
    cloudfd:
        image: cloudflare/cloudflared:2021.11.0-amd64
        restart: always
        command: tunnel run
        scale: 2                # Restart is requied after config updates, and takes approx 30, during when all the services are down!
                                # hence, restart seperately.
                                # Supported natively: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/deploy-cloudflared-replicas
        volumes:
            - ./config:/home/nonroot/.cloudflared
              # Cloudflared doesn't seem to have any unattended data that needs persistence, just admin-side config which are fed to it.
              # Hence, the volume will stay within the git.
              #    - ./_data # nowhere to point this to (yet), the folder on the host is there as a placeholder.
```

The local folder `./config` that is mounted all has permissions to `1000:1000
