### ISSUE TITLE
Argo tunnel/Access - Image breaks on every update

### ISSUE THREAD

**Issue by tomgrossman** [cloudflare/cloudflared#538]
In the last few version updates, the previous image tag just fails to start for this reason:

> ERR Initiating shutdown error="cloudflared has been updated to version 2021.12.3"

Using the following k8s config:
```yaml
spec:
  template:
    spec:
      containers:
      - name: tunnel
        image: cloudflare/cloudflared:2021.12.2
        args:
        - tunnel
        - '--config'
        - /etc/cloudflared/config.yaml
        - run
```
And every time there is an update to the image, even a patch one, the container just crashes and going into a CrashLoop until I update the image.
Is this by design? Can't older version work?
Why is there no `:latest` tag that I can use instead?

Something here is very weird.

Please advise, thanks.

**Comment by chungthuang** [comment]
Hi @tomgrossman, we are working on getting the latest tag. In the meantime, you can pass `--no-autoupdate` flag after the tunnel command to disable autoupdate.  For example:
```
- name: tunnel
  image: cloudflare/cloudflared:2021.12.3
  args:
  - tunnel
  - '--no-autoupdate'
  - '--config'
  - /etc/cloudflared/config.yaml
  - run
```
