### ISSUE TITLE
Gitlab Registry and Docker Registry behind zero trust fail

### ISSUE THREAD

**Issue by Dandevslack** [cloudflare/cloudflared#545]
## Issue
Gitlab container registry, Harbor Container Registry and Docker container registry do not work once a zero trust rule is created

## Expected result
We expected container registries to work behind zero trust rules using the docker cli

## Steps taken to fix the issue
I have setup multiple zero trust applications behind cloudflared (thanks!).  We are struggling with getting a registry product up and running when any authentication is required to login to the registry.  Specifically, we receive the following error:
```
Login did not succeed, error: Error response from daemon: Get https://gitlab-registry.url.com/v2/: unable to decode token response: invalid character '<' looking for beginning of value
```
The registry will work if we do not use a zero trust rule.  Our ingress is configured as follows:
```
tunnel: tunnel-id
credentials-file: /home/machine/.cloudflared/tunnel-id.json
ingress:
  - hostname: gitlab.url.com
    service: http://localhost:80
  - hostname: gitlab-registry.url.com
    service: http://localhost:5000
  - hostname: gitlab-ssh.url.com
    service: ssh://localhost:22
  - service: http_status:404
```
We have also attempted to change the registry url to tcp and a socks proxy, but none of these methods work.  When inspecting logs related to the gitlab registry we are receiving unauthorized errors.

We have a paid license with Gitlab and have delved into several support requests, which seem to indicate that this is a cloudflared issue.  

Other steps we have taken/tried:
1. Enable CORS for both origins (gitlab and registry)
2. Enable all header types

Any help would be appreciated and thanks again for the stellar product!
