### ISSUE TITLE
Creating route records defined in config file

### ISSUE THREAD

**Issue by w35l3y** [cloudflare/cloudflared#551]
Any chance to call something similar to `cloudflared tunnel --config /data/options.yaml run` and the command create route records automatically ?

options.yaml
```
# this is new feature (it is a suggestion!)
route: # does it make sense to be a list ?
  - dns: www.app.com # could it be read from ingress list instead ?
  - dns: www2.app.com # could it be read from ingress list instead ?
  - ld: # load balancer
    name: ...
    pool: ...
  - ip: 10.0.0.0/8

# everything else already exist
no-autoupdate: true
originRequest: {}
metrics: localhost:41705
ingress:
  - service: http://localhost:8123 # homeassistant
    hostname: www.app.com
  - service: http://localhost:3000 # nodejs
    hostname: www2.app.com
  - service: http_status:404
tunnel: my_tunnel
```
