### ISSUE TITLE
Proxy to a different path on the origin service

### ISSUE THREAD

**Issue by brenner-tobias** [cloudflare/cloudflared#563]
**Is your feature request related to a problem? Please describe.**
In the ingress rules, it would be great to have the option to define a location of the service and not "only" a URL limited to protocol, hostname and IP (for http), e.g. `http://192.168.178.1/nas`

**Describe the solution you'd like**
I do not think a new option is needed, it could just be a part of the `service` URL.

**Describe alternatives you've considered**
Could also be added using an additional variable, like it is done for `path` on the hostname.

**Additional context**
If I add a URL with a location attached, I get the error:
`http://192.168.178.1/nas is an invalid address, ingress rules don't support proxying to a different path on the origin service. The path will be the same as the eyeball request's path`

**Comment by nmldiegues** [comment]
Hello @brenner-tobias ,

Have you checked https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress ?
I believe the `path` configuration of a service does what you are mentioning.

**Comment by nmldiegues** [comment]
That's much clearer, thanks!

That's not possible, indeed.
Of course you can set that up by running a nginx or equivalent in localhost and doing those transformations.
cloudflared is not aiming to be a general proxy, but we'll keep this in mind should it overlap with something we can provide of value

**Comment by regnaio** [comment]
This proposed feature would be important and can help eliminate several DNS records for the same tunnel, e.g.

```yaml
ingress:
    - hostname: subdomain1.domain.com
      service: https://localhost:3001
    - hostname: subdomain2.domain.com
      service: https://localhost:3002
    - hostname: subdomain3.domain.com
      service: https://localhost:3003
    # etc...
```

**Comment by regnaio** [comment]
Can a `cloudflared` contributor please advise?

To implement this feature, should we use [ProxyHTTP function](https://github.com/cloudflare/cloudflared/blob/master/proxy/proxy.go#L61) as a starting point?

**Comment by nmldiegues** [comment]
> Can a `cloudflared` contributor please advise?
> 
> To implement this feature, should we use [ProxyHTTP function](https://github.com/cloudflare/cloudflared/blob/master/proxy/proxy.go#L61) as a starting point?

Yes, that is the starting point.

**Comment by regnaio** [comment]
@brenner-tobias @nmldiegues Thanks for the ideas!

I came up with a rough working proof-of-concept

https://github.com/cloudflare/cloudflared/compare/master...regnaio:regnaio/location

```yaml
ingress:
  - hostname: A.domain.com
    path: /B/.*
    service: https://localhost:3000
    location: /C
```

This allows an input URL like `A.domain.com/B/hello` to be mapped to `https://localhost:3000/C/hello`

This mapping is opinionated and not general, so it may not currently be fit for a PR. Also, I have not yet implemented any tests or strict checks on the newly added `Location` string field
