### ISSUE TITLE
Error parsing YAML in config file. Line 2: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by jrca025** [cloudflare/cloudflared#590]
When I try to run the tunnel that I created via cmd (as administator). This error pops up: "Error parsing YAML in config file at C:\Users\$USERNAME$\.cloudflared\config.yml" . Line 2: mapping values are not allowed in this context", I only encountered this on latest version of cloudflared for windows 64bit.

On previous version of cloudflared the process ran smoothly.

**Comment by nmldiegues** [comment]
Hello @jrca025 

Can you please follow the bug template and fill in the contents?
We would need your config to be able to reproduce the problem.

We have tests running in Windows that are passing, so this may be something specific to your config.

**Comment by jrca025** [comment]
hi @nmldiegues 

here is the config content, I just followed the steps in this doc https://developers.cloudflare.com/cloudflare-one/tutorials/rdp/

tunnel: tunnelID
  - hostname: testrdp.website.com
    service: rdp://localhost:3389
  - service: http_status:404

Running on the latest cloudflared-windows-amd64.exe version [2022.2.2]

**Comment by nmldiegues** [comment]
Yeah I can see the problem:  the developers.cloudflare.com page was migrated last week and we're finding some bugs with the migration.

In this case, the config snippet you copied has a problem, it's missing the `ingress:` keyword

It'll work if you do:
```
tunnel: 6ff42ae2-765d-4adf-8112-31c55c1551ef

ingress:
  - hostname: azure.widgetcorp.tech
    service: rdp://localhost:3389
  - service: http_status:404
  # Catch-all rule, which responds with 404 if traffic doesn't match any of
  # the earlier rules
```
