### ISSUE TITLE
kubectl port-forward and exec not working with cloudflared tunnel

### ISSUE THREAD

**Issue by tikrko** [cloudflare/cloudflared#648]
Hi,

I've deployed a Cloudflare tunnel to my Kubernetes cluster and I've been able to do basic operations like get/create/delete, and I'm able to retrieve logs too, but I'm getting errors while trying to `port-forward` or `exec` into a pod. 

It fails with:

```
error: error sending request: Post "https://my-cluster-address:6443/api/v1/namespaces/this-namespace/pods/httpbin-6fcc7cbb86-7ksnj/exec?command=bash&container=httpbin&stdin=true&stdout=true&tty=true": EOF
```

Same error for `port-forward`. 

This commands work as expected when not using `cloudflared`.

Fwiw, this is my config file:
```
tunnel: tunnel-UUID
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  - hostname: my-hostname
    service: tcp://kubernetes.default.svc:443
    originRequest:
      proxyType: socks
  - service: http_status:404
```

Is there any plan to support these commands? Am I missing something?

I can provide further logs if needed.

Thanks!
