### ISSUE TITLE
ingress rules clearification

### ISSUE THREAD

**Issue by Aeisu** [cloudflare/cloudflared#691]
I am trying to have cloudflared route any inbound connection directly to a game server i run off of my desktop. It runs well over my local network i'm just trying to figure out how to correctly write the rule to make things work. Nothing I try seems to work at all in all the tutorials and information on the wiki page
This is what i have so far 

 ingress:    
            -hostname: ffxi.isenguard.org
             service: tcp://192.168.1.66:54230

            -service: http_status:404

So the idea is to be forwarded to my local IP 192.168.1.66 to port 54230 which the game is running on, or even just to  my local machine would work too i think.

**Comment by SayakMukhopadhyay** [comment]
If you are seeing errors, please post there logs.

**Comment by Aeisu** [comment]
![Cloudflared Tunnel 1](https://user-images.githubusercontent.com/64471323/178123105-0f22cfca-cb76-4eb8-a5b1-a9e5716c088d.png)

**Comment by SayakMukhopadhyay** [comment]
Seems like your yaml is not correctly formatted. Try to put in in here http://www.yamllint.com/ and see what error it outputs and fix that. Else paste a screenshot of the config file as the configuration you posted in the question is not correctly formatted.

**Comment by Aeisu** [comment]
![Cloudflared Tunnel 2](https://user-images.githubusercontent.com/64471323/178141280-c3143d82-548b-4313-8a33-cdd63ab0360c.png)

**Comment by SayakMukhopadhyay** [comment]
As seen in yamllint, there is a major problem with your yaml.
```yaml
tunnel: what-your-tunnelid-was
credentials-file: cred-file-location
ingress:
  - hostname: ffxi.isenguard.org
    service: tcp://192.168.1.66:54230
  - service: http_status:404
```
As you can see, you need to properly indent your yaml file. Moreover, you need to have a space after "-".
