### ISSUE TITLE
cloudflared exiting with non-zero status code on successful update

### ISSUE THREAD

**Issue by antifob** [cloudflare/cloudflared#70]
An update done using `cloudflared update` returns a non-zero exit status.
If there are no updates, the exit status is zero.
Is it possible to make `cloudflared` return non-zero only on errors?

```
$ gzip -cd ../cloudflared-stable-linux-amd64.tgz | tar -f- -x
$ ls
cloudflared
$ sha1sum cloudflared
f526374f5af4c1638d4803f2ad29873b408c45f3  cloudflared
$ ./cloudflared update
INFO[0002] Updated to version 2019.1.0
$ echo $?
64
$ ./cloudflared update
$ echo $?
0
```

**Comment by sssilver** [comment]
Thanks for reporting this! Yes -- we are currently working to revamp the way we do update exit codes. Keep an eye out for a release.

**Comment by sssilver** [comment]
This has been fixed in our 2018.2.1 release.

**Comment by CanntAim** [comment]
Is there a regression bug regarding this? I have `ansible` script that upgrade all my services which includes `cloudflared`. The past two upgrade my `ansible` script has "failed" on the `upgrade` even though `cloudflared` upgrades to latest version. The error message informs me that `cloudflared` had a _non-zero_ error code. Subsequent runs of the playbook continues through the rest of the steps I have since the server is already upgraded.

Unfortunately I `exit`'d the terminal tab before saving the output anywhere, next time I run updates I can post back `stdout` result here. 

Relevant playbook steps:

```
- hosts: <my server name>
  become: yes
  tasks:
   - name: update cloudflared
     command: cloudflared update
   - name: restart cloudflared
     systemd:
       name: cloudflared
       state: restarted
       enabled: yes
```
