### ISSUE TITLE
💡--pidfile support for "cloudflared access"

### ISSUE THREAD

**Issue by ambis** [cloudflare/cloudflared#723]
**Describe the feature you'd like**
I would much rather like to write this task file like it's below the working example.

Currently working version:
```yaml
version: '3'
tasks:
  env:
    cmds:
      - cloudflared access tcp --hostname https://api.example.com --url 127.0.0.1:12345 &
      - defer: kill -15 $(pgrep -fl cloudflared | grep '127.0.0.1:12345' | cut -d' ' -f1)
      - HTTPS_PROXY=socks5://127.0.0.1:12345 "${SHELL}" # kubectl now works with the API
```

Oh boy if this would be possible:
```yaml
version: '3'
tasks:
  env:
    cmds:
      - cloudflared access tcp --hostname https://api.example.com --url 127.0.0.1:12345 --pidfile .cloudflared.pid &
      - defer: pkill -F .cloudflared.pid
      - HTTPS_PROXY=socks5://127.0.0.1:12345 "${SHELL}" # kubectl now works with the API
```

I have found myself using the socks tunnels for quite many things (Hashicorp Vault access for CI, kube API etc). This would be most useful feature to make supporting scripts so much cleaner.

Thanks.
