### ISSUE TITLE
🐛 Cannot use DNS in config.yaml

### ISSUE THREAD

**Issue by Apollorion** [cloudflare/cloudflared#748]
**Describe the bug**
If I use DNS in cloudflared's config yaml, I get the following error:
`standard_init_linux.go:228: exec user process caused: exec format error`

If I change this to an ip address, instead, it works fine.

**Environment and versions**
 - OS: Raspberry PI 4, MicroK8s 1.23
 - Version: `cloudflare/cloudflared:2022.3.0`

Note: the below manifest uses `example.com`. This is actually pointing to one of my domains, I've just redacted it.
Manifest:
```yaml
---
# More info on this can be found here
# https://github.com/cloudflare/argo-tunnel-examples/tree/master/named-tunnel-k8s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2022.3.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: tunnel-credentials
        - name: config
          configMap:
            name: cloudflared
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
# example webservice:
#    - hostname: tunnel.example.com
#      service: http://web-service:80
  config.yaml: |
    tunnel: home
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: piled.example.com
      service: http://192.168.229.88:8000
    - hostname: nextcloud.example.com
      service: http://nextcloud.nextcloud.svc.cluster.local:8080
    - hostname: tunnel.example.com
      service: hello_world
    - hostname: hello.example.com
      service: hello_world
    - service: http_status:404
```

the above offending line is `service: http://nextcloud.nextcloud.svc.cluster.local:8080`. If I was to change this to cluster IP, instead of dns, it works fine. `service: http://10.152.183.152:8080`.

The dns does resolve in cluster, so its not a resolving issue as far as I can tell.

```
; <<>> DiG 9.16.20 <<>> nextcloud.nextcloud.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42075
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 00a40dafcdd89092 (echoed)
;; QUESTION SECTION:
;nextcloud.nextcloud.svc.cluster.local. IN A

;; ANSWER SECTION:
nextcloud.nextcloud.svc.cluster.local. 5 IN A   10.152.183.152

;; Query time: 8 msec
;; SERVER: 10.152.183.10#53(10.152.183.10)
;; WHEN: Sun Sep 04 15:40:55 UTC 2022
;; MSG SIZE  rcvd: 131
```
