### ISSUE TITLE
Monitoring Tunnels with Grafana 

### ISSUE THREAD

**Issue by duydo-ct** [cloudflare/cloudflared#792]
I have set up monitoring Tunnels with Grafana.
I deploy `Cloudflared` on K8s with config `metrics: 0.0.0.0:2000`
How to expose this `<service-URL>:<service-port>` on K8s. ?
I see the step Setting Up Prometheus via the link https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/grafana/
```
  ## ADD HERE
  - job_name: '<job name>' ##NAME FOR JOB
    static_configs:
      - targets: ['<service-URL>:<service-port>']  ##PORT THAT TUNNEL SENDS METRICS TOO
```
