### ISSUE TITLE
🐛 Inconsistent behavior in docker compose

### ISSUE THREAD

**Issue by ashishjullia** [cloudflare/cloudflared#805]
**Describe the bug**

Check the screenshots mentioned below, I am facing different behaviour in both the scenarios.

**To Reproduce**
1. Configure 'docker compose and docker'
3. Run 'sudo docker compose up -d'
4. See error '502 Bad Gateway'
![image](https://user-images.githubusercontent.com/11252951/199867206-c9713ca8-40ab-408e-9bc0-af19b1d3a4c2.png)

If it's an issue with Cloudflare Tunnel:
6. Tunnel ID : 
7. cloudflared config: 

**Expected behavior**
Plex is working fine just with the name of the service when entered in Web GUI dashboard.
![image](https://user-images.githubusercontent.com/11252951/199866673-1aed8d9f-af8f-430a-9a14-9527674e92df.png)

`docker-compose.yml` for plex:
```
---
version: "3.7"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
      #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=<string>
    volumes:
      - ./plex-config:/config
    ports:
      - 32400:32400
        #- 1900:1900/udp
      - 3005:3005
        #- 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: unless-stopped
    networks:
      - plex-net

  tunnel:
    container_name: cloudflared-tunnel-plex
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<token-string>
    networks:
      - plex-net

networks:
  plex-net:
    name: plex-net
```

But it is not working fine with filerun:
![image](https://user-images.githubusercontent.com/11252951/199866961-ffe3089f-1e4f-46a9-a007-bd28bce2aef0.png)

`docker-compose.yml` for filerun:
```
---
version: "3.9"
services:
  web:
    image: filerun/filerun:arm64v8
    container_name: filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: your_mysql_database
      FR_DB_USER: your_mysql_username
      FR_DB_PASS: your_mysql_password
      APACHE_RUN_USER: pi
      APACHE_RUN_USER_ID: 1000
      APACHE_RUN_GROUP: pi
      APACHE_RUN_GROUP_ID: 1000
    depends_on:
      - db
    ports:
      - 8090:80
    volumes:
      - ./html:/var/www/html
      - /media/pi/64122F72122F47FE/photos-videos:/user-files
    networks:
      - filerun-net

  db:
    image: tobi312/rpi-mariadb:10.3
    container_name: rpi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: your_mysql_username
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_DATABASE: your_mysql_database
      PUID: 1000
      PGID: 1000
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - filerun-net

  tunnel:
    container_name: cloudflared-tunnel-filerun
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<token-string>
    networks:
      - filerun-net

networks:
  filerun-net:
    name: filerun-net
```

Expected ==> it should work fine in both scenarios.

**Environment and versions**
 - OS: [e.g. MacOS] Raspberry Pi4
 - Architecture: [e.g. AMD, ARM] ARM
 - Version: [e.g. 2022.02.0] Lastest PiOS

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**
One more thing, when I'm putting the Raspberry Pi's IP address in the web GUI, it is working find for filerun as well.

I thought a lot on this, can state a solid answer as why this behavior.
