### ISSUE TITLE
🐛Failed to send ICMP reply error="funnel not found"

### ISSUE THREAD

**Issue by chrbongardt** [cloudflare/cloudflared#807]
**Describe the bug**
After running the tunnel I constantly see this error message spamming in the log `ERR Failed to send ICMP reply error="funnel not found" dst=1.0.0.1:0`. It happens with different tunnels. However the tunnels work. 

**To Reproduce**
1. Configure
2. Run
3. See error
4. Tunnel ID : 2a202cac-8857-4f86-99ef-9c3e6ad306bd
5. Cloudflared config: 
```
tunnel: 2a202cac-8857-4f86-99ef-9c3e6ad306bd
credentials-file: /Users/chrbongardt/.cloudflared/2a202cac-8857-4f86-99ef-9c3e6ad306bd.json
ingress:
  - hostname: 80.xxxxx.com
    service: http://localhost:80
  - hostname: 3000.xxx.com
    service: http://localhost:3000
  - hostname: 1234.xxx.com
    service: http://localhost:1235
  - hostname: 1235.xxx.com
    service: http://localhost:1235
  - service: http_status:404
  ```

**Expected behavior**
A log output without the error constantly appearing.

**Environment and versions**
 - OS: MAC OS
 - Architecture: ARM
 - Version: 2022.10.3 (built 2022-10-26T09:40:17Z) installed with homebrew

**Logs and errors**
2022-11-08T15:09:08Z INF Starting tunnel tunnelID=2a202cac-8857-4f86-99ef-9c3e6ad306bd
2022-11-08T15:09:08Z INF Version 2022.10.3
2022-11-08T15:09:08Z INF GOOS: darwin, GOVersion: go1.19.3, GoArch: arm64
2022-11-08T15:09:08Z INF Settings: map[cred-file:/Users/chrbongardt/.cloudflared/2a202cac-8857-4f86-99ef-9c3e6ad306bd.json credentials-file:/Users/chrbongardt/.cloudflared/2a202cac-8857-4f86-99ef-9c3e6ad306bd.json]
2022-11-08T15:09:08Z INF cloudflared will not automatically update if installed by a package manager.
2022-11-08T15:09:08Z INF Generated Connector ID: b9a3420b-ca96-4e3f-b6c9-166f81d0d59b
2022-11-08T15:09:08Z INF Initial protocol quic
2022-11-08T15:09:08Z INF ICMP proxy will use 192.168.30.68 as source for IPv4
2022-11-08T15:09:08Z INF ICMP proxy will use fe80::ce:1522:34a:ce98 in zone en0 as source for IPv6
2022-11-08T15:09:08Z INF Created ICMP proxy listening on 192.168.30.68:0
2022-11-08T15:09:08Z INF Created ICMP proxy listening on [fe80::ce:1522:34a:ce98%en0]:0
2022-11-08T15:09:08Z INF Starting metrics server on 127.0.0.1:63434/metrics
2022-11-08T15:09:08Z ERR update check failed error="no release found"
2022-11-08T15:09:09Z INF Connection 03cd7460-d00b-4453-8b81-d868ee868740 registered connIndex=0 ip=198.41.200.233 location=MIA
2022-11-08T15:09:09Z ERR Failed to send ICMP reply error="funnel not found" dst=1.0.0.1:0
2022-11-08T15:09:09Z INF Connection 7b51c33d-583e-43f7-a02f-286908545600 registered connIndex=1 ip=198.41.192.227 location=ATL
2022-11-08T15:09:10Z INF Connection 220d49a4-cedc-43e1-aa0e-58c488a15a4a registered connIndex=2 ip=198.41.200.73 location=MIA
2022-11-08T15:09:11Z INF Connection 26108535-a0fb-461d-a4e0-3f12a9efd965 registered connIndex=3 ip=198.41.192.67 location=ATL
2022-11-08T15:09:11Z ERR Failed to send ICMP reply error="funnel not found" dst=1.0.0.1:0
2022-11-08T15:09:14Z ERR Failed to send ICMP reply error="funnel not found" dst=1.0.0.1:0
2022-11-08T15:09:16Z ERR Failed to send ICMP reply error="funnel not found" dst=1.0.0.1:0
2022-11-08T15:09:18Z ERR Failed to send ICMP reply error="funnel not found" dst=1.0.0.1:0
2022-11-08T15:09:20Z ERR Failed to send ICMP reply error="funnel not found" dst=1.0.0.1:0
2022-11-08T15:09:22Z ERR Failed to send ICMP reply error="funnel not found" dst=1.0.0.1:0
