### ISSUE TITLE
💡 Is there a easier way to ssh with argo tunnel?

### ISSUE THREAD

**Issue by fscarmen** [cloudflare/cloudflared#936]
**Describe the feature you'd like**
I created the tunnel in a with the following configuration file on VPS A
```
tunnel: 6ff42ae2-765d-4adf-8112-31c55c1551ef
credentials-file: /root/.cloudflared/6ff42ae2-765d-4adf-8112-31c55c1551ef.json
Protocol: http2

ingress:
  - hostname: gitlab.widgetcorp.tech
    service: http://localhost:80
  - hostname: gitlab-ssh.widgetcorp.tech
    service: ssh://localhost:22
  - Service: http_status:404
```
On VPS B I want to tunnel ssh to A. Now what I'm doing is running
```
cloudflared access ssh on B --hostname gitlab-ssh.widgetcorp.tech --listener localhost:33333
ssh root@localhost -p 33333
```

Is there a simpler way to do this with a single command that doesn't require creating a port locally?
