### ISSUE TITLE
💡General `Upgrade` header support

### ISSUE THREAD

**Issue by aofei** [cloudflare/cloudflared#990]
**Describe the feature you'd like**

I attempted to serve my [Headscale](https://github.com/juanfont/headscale) and [Tailscale DERP Servers](https://tailscale.com/kb/1232/derp-servers/) behind Cloudflare Tunnels, but unfortunately, they are not functioning as expected. The main issue stems from their usage of the `Upgrade` header, similar to the WebSocket protocol. However, unlike the standard `Upgrade: websocket` value, they employ custom values such as `Upgrade: tailscale-control-protocol` and `Upgrade: derp`.

Currently `cloudflared` is limited to handling only the standard `Upgrade: websocket` value. I'm curious if there would be any consequences of not detecting the value of the `Upgrade` header. As far as I know [`net/http/httputil.ReverseProxy`](https://pkg.go.dev/net/http/httputil#ReverseProxy) doesn't detect these values, and everything seems to work fine. In fact, Cloudflare Proxy didn't detect them either.

**Describe alternatives you've considered**

Currently I'm using Cloudflare Proxy and things are working fine. But I still prefer to use Cloudflare Tunnel to serve my services.

**Additional context**

N/A

**Comment by allamedo** [comment]
I'm not sure if this would be related to your problem, but have you tried to enable gRPC under your domain's settings on the Cloudflare main panel, under the "network" tab.

**Comment by aofei** [comment]
> have you tried to enable gRPC under your domain's settings on the Cloudflare main panel, under the "network" tab.

I don't think that has anything to do with this issue, all my zones have those settings enabled.

This issue seems to be a local problem. It appears that cloudflared is rejecting requests with `Upgrade` values other than `Upgrade: websocket`.

**Comment by pfrankw** [comment]
Hello @aofei , did you manage to resolve your issue? If yes how?
Thanks

**Comment by aofei** [comment]
> Hello @aofei , did you manage to resolve your issue? If yes how? Thanks

Nope. Not only Cloudflare Tunnel, but now even Cloudflare Proxy doesn't support non-standard `Upgrade` headers anymore.

I've moved my Headscale to [fly.io](https://fly.io) and then disabled Cloudflare Proxy (grey cloud), so I no longer have a need for this feature.

**Comment by SSIvanov19** [comment]
I am using Cloudflare Tunnel to use with [Coder](https://coder.com). But it gives me the following warning, that seems to be related to this issue:
```
Node uses WebSockets because the "Upgrade: DERP" header may be blocked on the load balancer.
```
Here are the logs from Coder:
```
derphttp.Client.Connect: connecting to https://coder.example.com/derp
derphttp.Client.Connect: TLS version 0x304
derpclient: got cert example.com
derpclient: got cert WE1
derpclient: got cert GTS Root R4
derphttp.Client.Connect: not using fast start
derphttp.Client.Connect: DERP server returned status 426
We'll use WebSockets on the next connection attempt: GET failed with status code 426 (a proxy could be disallowing the use of 'Upgrade: derp'): DERP requires connection upgrade
```

**Comment by minhio** [comment]
in for answer

**Comment by jin-li** [comment]
OMG I really hope I had seen this issue earlier. I have spent at least one week to try to make headscale work with Cloudflare Tunnel but never succeeded. Anyway, still hope this feature can be supported.

**Comment by Sharpie** [comment]
For a minute, I thought `cloudflared` would allow me to stop managing a floating IP, reverse proxy, firewall rules, and LetsEncrypt certificate to front Headscale and just ingress traffic directly to the controller.

But, alas, the setup fails due to stripped `Upgrade` headers:

```
2025-10-26T16:45:52Z WRN home/runner/work/headscale/headscale/hscontrol/noise.go:66 > No Upgrade header in TS2021 request. If headscale is behind a reverse proxy, make sure it is configured to pass WebSockets through.
```

Looks like `ngrok` is able to handle this usecase.

**Comment by jin-li** [comment]
> For a minute, I thought `cloudflared` would allow me to stop managing a floating IP, reverse proxy, firewall rules, and LetsEncrypt certificate to front Headscale and just ingress traffic directly to the controller.
> 
> But, alas, the setup fails due to stripped `Upgrade` headers:
> 
> ```
> 2025-10-26T16:45:52Z WRN home/runner/work/headscale/headscale/hscontrol/noise.go:66 > No Upgrade header in TS2021 request. If headscale is behind a reverse proxy, make sure it is configured to pass WebSockets through.
> ```
> 
> Looks like `ngrok` is able to handle this usecase.

Were you able to make `ngrok` working in this use case? Can you elaborate?

**Comment by Sharpie** [comment]
> Were you able to make `ngrok` working in this use case? Can you elaborate?

It was a matter of running the `ngrok/ngrok` container with the command line set to deliver `http` traffic to port 8080 on the Headscale container.

**Comment by Sharpie** [comment]
Here's a more complete example, now that I've got things cleaned up a bit. To start with, you'll need to go to "Endpoints & Traffic Policy" in the Ngrok dashboard and create a "Cloud Endpoint". By default, this will route traffic to the `https://default.internal` URL used below:

```yaml
---
services:
  headscale:
    container_name: headscale
    image: ghcr.io/juanfont/headscale:v0.26
    restart: unless-stopped
    volumes:
      - data:/var/lib/headscale
    configs:
      - source: headscale-config
        target: /etc/headscale/config.yaml
    networks:
      - headscale
    command:
      - serve

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    networks:
      - headscale
    # Define NGROK_AUTHTOKEN here.
    env_file: './ngrok.env'
    command:
      - http
      - 'headscale:8080'
      # This connects to configuration in ngrok "Endpoints & Traffic Policy"
      - '--url=https://default.internal'

networks:
  headscale:

volumes:
  data:

configs:
  headscale-config:
    # See: https://github.com/juanfont/headscale/blob/v0.26.1/config-example.yaml
    file: './config.yaml'
```

CloudflareD setup was just as simple... except for the whole blocking issue with `Upgrade` headers getting scrubbed.
